kind: pipeline
type: docker
name: default
environment:
  INFLUX_ORG: "primary_org"
  INFLUX_BUCKET: "primary_bucket"
  INFLUX_USER: "user"

services:
- name: influxdb2
  image: "quay.io/influxdb/influxdb:2.0.0-beta"
  commands:
    - sleep 30
    - echo influx setup -f -b $INFLUX_BUCKET -u $INFLUX_USER -p password -o $INFLUX_ORG
    - influx setup -f -b $INFLUX_BUCKET -u $INFLUX_USER -p password -o $INFLUX_ORG
    - sleep 1
    - echo INFLUX_TOKEN=$(influx auth list | awk 'NR==2{print $2}') > $DRONE_STEP_NAME.env

steps:
- name: check_influxdb2
  image: byrnedo/alpine-curl
  depends_on:
    - influxdb2
  commands:
    - sleep 30
    - curl http://influxdb2:9999/api/v2/setup
    - sleep 5
    - curl http://influxdb2:9999/api/v2/setup
    - sleep 5
    - curl http://influxdb2:9999/api/v2/setup
    - sleep 5
    - curl http://influxdb2:9999/api/v2/setup
    - sleep 5

- name: test
  image: rust:1
  depends_on:
    - influxdb2
  commands:
    - sleep 40
    - source influxdb2.env
    - env
    - cargo test --verbose --all


